# Generated by Django 6.0.3 on 2026-03-09 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='chapter_file',
            field=models.FileField(blank=True, null=True, upload_to='chapter_files/'),
        ),
    ]
