# Generated by Django 6.0.3 on 2026-03-11 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_order_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPreviewPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='product_preview_pages/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preview_pages', to='core.product')),
            ],
            options={
                'ordering': ['page_number'],
                'unique_together': {('product', 'page_number')},
            },
        ),
    ]
