# Generated by Django 6.0.3 on 2026-03-14 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_productpreviewpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_read_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recent_reads', to='core.chapter')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recent_reads', to='core.customerprofile')),
                ('digital_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recent_reads', to='core.digitalbook')),
            ],
            options={
                'ordering': ['-last_read_at'],
                'unique_together': {('customer', 'chapter')},
            },
        ),
    ]
