# Generated by Django 6.0.3 on 2026-03-14 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_recentread'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='seller_license',
            field=models.FileField(blank=True, null=True, upload_to='seller_licenses/'),
        ),
    ]
